version: "3.8"

services:
  web:
    build:
      context: ./app
    container_name: flask_inventory
    ports:
      - "5000:5000"
    volumes:
      - ./app/uploads:/app/static/uploads
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_inventory
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventorydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
